//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftinsaBadgesWeb
{


    public partial class Badges
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblPesquisa;

        protected global::System.Web.UI.WebControls.TextBox txtPesquisa;

        protected global::System.Web.UI.WebControls.Button btnPesquisa;

        protected global::System.Web.UI.WebControls.Button btnLimparPesquisa;

        protected global::System.Web.UI.WebControls.GridView gvBadges;

        protected global::System.Web.UI.WebControls.Label lblIdBadgeLabel;

        protected global::System.Web.UI.WebControls.TextBox txtIdBadge;

        protected global::System.Web.UI.WebControls.Label lblNome;

        protected global::System.Web.UI.WebControls.TextBox txtNome;

        protected global::System.Web.UI.WebControls.Label lblDescricao;

        protected global::System.Web.UI.WebControls.TextBox txtDescricao;

        protected global::System.Web.UI.WebControls.Label lblPontos;

        protected global::System.Web.UI.WebControls.TextBox txtPontos;

        protected global::System.Web.UI.WebControls.Label lblPath;

        protected global::System.Web.UI.WebControls.DropDownList ddlPath;

        protected global::System.Web.UI.WebControls.Label lblNivel;

        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;

        protected global::System.Web.UI.WebControls.Label lblEstado;

        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        protected global::System.Web.UI.WebControls.Button btnInserir;

        protected global::System.Web.UI.WebControls.Button btnAtualizar;

        protected global::System.Web.UI.WebControls.Button btnLimparFormulario;

        protected global::System.Web.UI.WebControls.Label lblMensagem;
    }
}
