FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR C:\\inetpub\\wwwroot
COPY . .
COPY docker-entrypoint.ps1 C:\\docker-entrypoint.ps1

EXPOSE 80
ENTRYPOINT ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "C:\\docker-entrypoint.ps1"]
